#!/usr/bin/env bash
# Backup to a remote location using Borg.


# Configs
VERSION=8
source /etc/backupctl/conf
export BORG_RSH="ssh -i ${SSH_PATH_TO_KEY}"
export BORG_REPO=${SSH_PATH_TO_REPO}
export BORG_PASSPHRASE=${PASSPHRASE}


case $1 in
  "init")
    borg init --encryption=repokey ::
  ;;
  "create")
    # Backup system
    BACKUP_NAME=$(hostname -s)-$(date +"%H:%M:%S-%d-%b-%Y")
    borg create -v --stats --progress ::${BACKUP_NAME} / --exclude-from /etc/backupctl/excludefile --compression lz4
    exit 0
  ;;
  "prune")
    # Prune extra backups Keep all backups in the last 7 days and 3 monthly
    borg prune -v --stats --keep-within=7d --keep-monthly=3 --prefix $(hostname -s)- ${@:2}
    exit 0
  ;;
  "list")
    borg list ::
    exit 0
  ;;
  "info")
    borg info ::$2
    exit 0
  ;;
  "--version")
    echo $VERSION
  ;;
  "--help")
    echo "backupctl [ init | create | prune | list | info <NAME BACKUP> | --version | --help ]"
    exit 0
  ;;
  "_export_borg_variables")
    cat <<EOF
export BORG_RSH="ssh -i ${SSH_PATH_TO_KEY}"
export BORG_REPO=${SSH_PATH_TO_REPO}
export BORG_PASSPHRASE=${PASSPHRASE}
EOF
    exit 0
  ;;
  *)
    echo "Unknown command..."
    exit 1
esac
